In [19]:
import pandas as pd

df = pd.read_csv("Sales_data (1).csv")
df.head()

,order_id,order_date,ship_date,customer,manufactory,product_name,segment,category,subcategory,region,zip,city,state,country,discount,profit,quantity,sales,profit_margin
0,US-2020-103800,1/3/2019,1/7/2019,Darren Powers,Message Book,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Consumer,Office Supplies,Paper,Central,77095,Houston,Texas,United States,0.2,5.5512,2,16.448,0.3375
1,US-2020-112326,1/4/2019,1/8/2019,Phillina Ober,GBC,GBC Standard Plastic Binding Systems Combs,Home Office,Office Supplies,Binders,Central,60540,Naperville,Illinois,United States,0.8,-5.4870,2,3.540,-1.5500
2,US-2020-112326,1/4/2019,1/8/2019,Phillina Ober,Avery,Avery 508,Home Office,Office Supplies,Labels,Central,60540,Naperville,Illinois,United States,0.2,4.2717,3,11.784,0.3625
3,US-2020-112326,1/4/2019,1/8/2019,Phillina Ober,SAFCO,SAFCO Boltless Steel Shelving,Home Office,Office Supplies,Storage,Central,60540,Naperville,Illinois,United States,0.2,-64.7748,3,272.736,-0.2375
4,US-2020-141817,1/5/2019,1/12/2019,Mick Brown,Avery,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Consumer,Office Supplies,Art,East,19143,Philadelphia,Pennsylvania,United States,0.2,4.8840,3,19.536,0.2500

In [20]:
#About dataset
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       9994 non-null   object
 1   order_date     9994 non-null   object
 2   ship_date      9994 non-null   object
 3   customer       9994 non-null   object
 4   manufactory    9994 non-null   object
 5   product_name   9994 non-null   object
 6   segment        9994 non-null   object
 7   category       9994 non-null   object
 8   subcategory    9994 non-null   object
 9   region         9994 non-null   object
 10  zip            9994 non-null   int64
 11  city           9994 non-null   object
 12  state          9994 non-null   object
 13  country        9994 non-null   object
 14  discount       9994 non-null   float64
 15  profit         9994 non-null   float64
 16  quantity       9994 non-null   int64
 17  sales          9994 non-null   float64
 18  profit_margin  9994 non-null   float64
dtypes: float64(4), int64(2), object(13)
memory usage: 1.4+ MB

,zip,discount,profit,quantity,sales,profit_margin
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,55190.371723,0.156203,28.656896,3.789574,229.858001,0.120314
std,32063.705315,0.206452,234.260108,2.225110,623.245101,0.466754
min,1040.000000,0.000000,-6599.978000,1.000000,0.444000,-2.750000
25%,23223.000000,0.000000,1.728750,2.000000,17.280000,0.075000
50%,56430.500000,0.200000,8.666500,3.000000,54.490000,0.270000
75%,90008.000000,0.200000,29.364000,5.000000,209.940000,0.362500
max,99301.000000,0.800000,8399.976000,14.000000,22638.480000,0.500000

In [21]:
#Missing values count
df.isna().sum()

order_id         0
order_date       0
ship_date        0
customer         0
manufactory      0
product_name     0
segment          0
category         0
subcategory      0
region           0
zip              0
city             0
state            0
country          0
discount         0
profit           0
quantity         0
sales            0
profit_margin    0
dtype: int64

In [22]:
#Remove duplicate
df = df.drop_duplicates()

In [23]:
# Convert dates
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [24]:
print("Total Sales:", df['sales'].sum())
print("Total Profit:", df['profit'].sum())
print("Total Orders:", df['order_id'].nunique())
print("Total Products:", df['product_name'].nunique())

Total Sales: 2296919.4883
Total Profit: 286409.08050000004
Total Orders: 5009
Total Products: 1849

In [25]:
#Top 10 products
top_products = (df.groupby('product_name')['sales'].sum().sort_values(ascending=False).head(10))
print(top_products)

product_name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: sales, dtype: float64

In [26]:
#Best region
region_sales = (df.groupby('region')['sales'].sum().sort_values(ascending=False))
print(region_sales)

region
West       725457.8245
East       678499.8680
Central    501239.8908
South      391721.9050
Name: sales, dtype: float64

In [34]:
#Category analysis
category_sales = (df.groupby('category')['sales'].sum().sort_values(ascending=False))
print(category_sales)

category
Technology         836154.0330
Furniture          741718.4233
Office Supplies    719047.0320
Name: sales, dtype: float64

In [28]:
#Monthly trend
df['month'] = df['order_date'].dt.month
monthly_sales = (df.groupby('month')['sales'].sum())
print(monthly_sales)

month
1      94924.8356
2      59751.2514
3     205005.4888
4     137480.7566
5     155028.8117
6     152718.6793
7     147238.0970
8     159044.0630
9     307649.9457
10    200322.9847
11    352461.0710
12    325293.5035
Name: sales, dtype: float64

In [32]:
#State-wise sales (Top 10)
state_sales = (df.groupby('state')['sales'].sum().sort_values(ascending=False).head(10))
print(state_sales)

state
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             77976.7640
Michigan         76269.6140
Virginia         70636.7200
Name: sales, dtype: float64

In [35]:
#Correlation Analysis
print(df[['sales','profit','quantity','discount']].corr())

             sales    profit  quantity  discount
sales     1.000000  0.479067  0.200808 -0.028197
profit    0.479067  1.000000  0.066241 -0.219481
quantity  0.200808  0.066241  1.000000  0.008680
discount -0.028197 -0.219481  0.008680  1.000000

In [33]:
#Profit Margin
profit_margin = (df['profit'].sum()/df['sales'].sum())*100
print("Profit Margin:", round(profit_margin,2),"%")

Profit Margin: 12.47 %

--------------------------------------------------------------

Business Insights

Key Findings
1. Technology category generated the highest sales.
2. West region contributed the most revenue.
3. Canon imageCLASS printer was among the top-selling products.
4. Sales showed strong growth during year-end months.
5. Higher discounts often reduced profitability.